name: Build Aether Engine

on:
  pull_request:
    branches:
      - "**"

  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false

      matrix:
        include:
          - target: windows
            build-name: Build for Windows
            cmake-preset: msvc
            runs-on: windows-latest

          - target: linux
            build-name: Build for Ubuntu Linux
            cmake-preset: gnu
            runs-on: ubuntu-latest

          - target: macOS
            build-name: Build for macOS
            cmake-preset: clang
            runs-on: macos-latest
    
    name: ${{ matrix.build-name }}
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Extract git hash
        id: git
        shell: bash
        run: echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup MSVC
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y \
            gcc-16.1.0 \
            g++-16.1.0 \
            libx11-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev \
            libgl1-mesa-dev
      
      - name: Install Pillow
        run: python -m pip install pillow

      - name: Build
        run: |
          cmake --preset ${{ matrix.cmake-preset }}-release
          cmake --build --preset ${{ matrix.cmake-preset }}-release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: aether-engine.${{ matrix.target }}.${{ steps.git.outputs.sha }}
          path: build/${{ matrix.cmake-preset }}-release/bin/engine
